import type { LivePlatformConfig } from '../live/config'

export const BILIBILI_PLATFORM_CONFIG: LivePlatformConfig = {
  name: '哔哩哔哩直播',
  maxLength: 1000,
  chatRoots: [
    '#chat-items',
    '#chat-history-list',
    '.chat-history-list',
    '.chat-items',
    "[class*='chat-history']",
    "[class*='danmaku-list']",
  ],
  videoRoots: [
    '#live-player',
    '.live-player-mounter',
    '.bpx-player-container',
    '.bilibili-live-player-video-area',
    "[class*='live-player']",
    "[class*='player-container']",
  ],
  overlayMessages: [
    '.bili-danmaku-x-dm',
    '.bili-danmaku-x-dm-content',
    '.b-danmaku',
    '.bilibili-player-video-danmaku .b-danmaku',
    '.bpx-player-dm-wrap .bili-danmaku-x-dm',
    ".bilibili-live-player-video-danmaku [class*='danmaku-item']",
    ".bpx-player-dm-wrap [class*='danmaku-item']",
    "[class*='video-danmaku-item']",
  ],
  messages: [
    '.danmaku-item',
    '.chat-item',
    '[data-danmaku]',
    "[data-id][class*='danmaku']",
    "[class*='message-item']",
  ],
  messageText: [
    '.danmaku-content',
    '.danmaku-item-right',
    '.message-content',
    "[class*='danmaku-content']",
    "[class*='danmakuContent']",
  ],
  userNames: [
    '.user-name',
    '.username',
    '.uname',
    '[data-username]',
    '[data-user-name]',
    '[data-nickname]',
    '[data-author-name]',
    "[class*='user-name' i]",
    "[class*='userName' i]",
    "[class*='username' i]",
    "[class*='nickname' i]",
    "[class*='author-name' i]",
    "a[href*='space.bilibili.com' i]",
    "a[href*='/user/' i]",
  ],
  inputs: [
    'textarea.chat-input',
    '.chat-input-ctnr textarea',
    '.bpx-player-dm-input',
    '.bilibili-player-video-danmaku-input',
    '.bpx-player-ctrl-dm-input input',
    '.bpx-player-ctrl-dm-input textarea',
    ".bpx-player-ctrl-dm-input [contenteditable]:not([contenteditable='false'])",
    ".bpx-player-ctrl-dm-input [role='textbox']",
    "textarea[placeholder*='弹幕']",
    "textarea[placeholder*='说点什么']",
    "[contenteditable]:not([contenteditable='false'])[data-placeholder*='弹幕']",
    ".chat-input[contenteditable]:not([contenteditable='false'])",
    "[role='textbox'][data-placeholder*='弹幕']",
  ],
  sendButtons: [
    ".chat-input-ctnr button[type='submit']",
    '.chat-input-ctnr .bl-button--primary',
    '.bpx-player-dm-btn',
    '.bpx-player-ctrl-dm-btn',
    '.send-btn',
    "button[class*='send']",
    "[class*='send-button']",
  ],
}
